name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0.x'
  RUST_VERSION: 'stable'
  PYTHON_VERSION: '3.12'

jobs:
  rust-tests:
    name: Rust Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install uv
        run: pip install uv
      
      - name: Install Volatility3
        run: uv pip install --system volatility3
      
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust-bridge/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Run Rust Tests
        working-directory: rust-bridge
        run: cargo test --verbose
      
      - name: Run Clippy
        working-directory: rust-bridge
        run: cargo clippy -- -D warnings
      
      - name: Check Formatting
        working-directory: rust-bridge
        run: cargo fmt -- --check
      
      - name: Generate Rust Coverage
        working-directory: rust-bridge
        shell: bash
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin --locked
          fi
          cargo tarpaulin --out xml --output-dir ./coverage --exclude-files ../PowerShell.MemoryAnalysis
      
      - name: Upload Rust Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./rust-bridge/coverage/cobertura.xml
          flags: rust-tests-${{ matrix.os }}
          fail_ci_if_error: false

  csharp-tests:
    name: C# Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore Dependencies
        run: dotnet restore tests/MemoryAnalysis.Tests/MemoryAnalysis.Tests.csproj
      
      - name: Build Tests
        run: dotnet build tests/MemoryAnalysis.Tests/MemoryAnalysis.Tests.csproj --no-restore
      
      - name: Run C# Tests with Coverage
        run: dotnet test tests/MemoryAnalysis.Tests/MemoryAnalysis.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults
      
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./TestResults/*/coverage.cobertura.xml
          flags: csharp-tests-${{ matrix.os }}
          fail_ci_if_error: false

  build-module:
    name: Build PowerShell Module
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    needs: [rust-tests, csharp-tests]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install uv
        run: pip install uv
      
      - name: Install Volatility3
        run: uv pip install --system volatility3
      
      - name: Install build essentials (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Build Rust Bridge
        working-directory: rust-bridge
        run: cargo build --release
      
      - name: Build PowerShell Module
        working-directory: PowerShell.MemoryAnalysis
        run: dotnet publish -c Release -o publish
      
      - name: Copy Rust DLL (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Copy-Item rust-bridge/target/release/rust_bridge.dll PowerShell.MemoryAnalysis/publish/
        shell: pwsh
      
      - name: Copy Rust Library (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp rust-bridge/target/release/librust_bridge.so PowerShell.MemoryAnalysis/publish/
      
      - name: Copy Rust Library (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cp rust-bridge/target/release/librust_bridge.dylib PowerShell.MemoryAnalysis/publish/
      
      - name: Install PowerShell 7.6 Preview (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          winget install --id Microsoft.PowerShell.Preview --version 7.6.0.5 --silent --accept-source-agreements --accept-package-agreements
          # Refresh PATH to pick up pwsh-preview
          $env:PATH = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          pwsh-preview -Version
      
      - name: Install PowerShell 7.6 Preview (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask powershell@preview
      
      - name: Install PowerShell 7.6 Preview (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.6.0-preview.5/powershell-preview_7.6.0-preview.5-1.deb_amd64.deb
          sudo dpkg -i powershell-preview_7.6.0-preview.5-1.deb_amd64.deb
          sudo apt-get install -f -y
      
      - name: Generate MAML Help (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pwsh-preview -Command {
            Install-Module -Name platyPS -Force -Scope CurrentUser
            Set-Location "$env:GITHUB_WORKSPACE"
            ./scripts/Generate-Help.ps1
          }
      
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MemoryAnalysis-${{ matrix.os }}
          path: PowerShell.MemoryAnalysis/publish/
          retention-days: 7

  integration-tests:
    name: PowerShell Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    needs: build-module
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install PowerShell 7.6 Preview (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          winget install --id Microsoft.PowerShell.Preview --version 7.6.0.5 --silent --accept-source-agreements --accept-package-agreements
          # Refresh PATH
          $env:PATH = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
      
      - name: Install PowerShell 7.6 Preview (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask powershell@preview
      
      - name: Install PowerShell 7.6 Preview (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.6.0-preview.5/powershell-preview_7.6.0-preview.5-1.deb_amd64.deb
          sudo dpkg -i powershell-preview_7.6.0-preview.5-1.deb_amd64.deb
          sudo apt-get install -f -y
      
      - name: Verify PowerShell Installation (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pwsh-preview -Version
      
      - name: Verify PowerShell Installation (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          /usr/local/bin/pwsh-preview -Version
      
      - name: Verify PowerShell Installation (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pwsh-preview -Version
      
      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -MinimumVersion 5.0 -Scope CurrentUser
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: MemoryAnalysis-${{ matrix.os }}
          path: PowerShell.MemoryAnalysis/publish/
      
      - name: Run Integration Tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pwsh-preview -Command {
            Import-Module Pester -MinimumVersion 5.0
            Set-Location "$env:GITHUB_WORKSPACE"
            Invoke-Pester -Path tests/integration-tests/Module.Tests.ps1 -CI
          }
      
      - name: Run Integration Tests (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          /usr/local/bin/pwsh-preview -Command {
            Import-Module Pester -MinimumVersion 5.0
            Set-Location "$env:GITHUB_WORKSPACE"
            Invoke-Pester -Path tests/integration-tests/Module.Tests.ps1 -CI
          }
      
      - name: Run Integration Tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pwsh-preview -Command {
            Import-Module Pester -MinimumVersion 5.0
            Set-Location "$env:GITHUB_WORKSPACE"
            Invoke-Pester -Path tests/integration-tests/Module.Tests.ps1 -CI
          }
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: tests/integration-tests/TestResults/
          retention-days: 7

  benchmark:
    name: Performance Benchmarks
    runs-on: windows-latest
    needs: build-module
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install PowerShell 7.6 Preview
        shell: pwsh
        run: |
          winget install --id Microsoft.PowerShell.Preview --version 7.6.0.5 --silent --accept-source-agreements --accept-package-agreements
          # Refresh PATH
          $env:PATH = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: MemoryAnalysis-windows-latest
          path: PowerShell.MemoryAnalysis/publish/
      
      - name: Run Benchmarks
        shell: pwsh
        run: |
          pwsh-preview -Command {
            Set-Location "$env:GITHUB_WORKSPACE"
            ./benchmarks/Measure-Performance.ps1
          }
      
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/benchmark-results-*.json
          retention-days: 30
